### ISSUE TITLE
Needs Uniform Handling

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/wp-events#5]
Handlers hooked with `EventManager#attach()` must all receive 1 parameter: the `Event` object.

**Comment by mecha** [comment]
One thing that confuses me with PSR-14 is the `$argv` parameter in [`EventManagerInterface#trigger()`][1].

According to the draft of the standard, regarding implements of `EventInterface`:

> OPTIONALLY the event can have additional parameters for use within the event.

So I'm not sure that the difference is between the event parameters and the `$argv` parameter in `EventManagerInterface#trigger()`. But on thing is for sure, the `Event` object can be created before hand and then triggered or even reused multiple times; so perhaps that's the intended difference: the `$argv` parameter is to be used to specify arguments at "trigger time", while params in the `Event` object can be given before hand.

@XedinUnknown What do you think? I'm bringing this up because only one set of data can be given to a triggered event, at least in WordPress. So we'd have to decide on which set of parameters gets passed to the event. This of course only applies when the first argument in `EventManagerInterface#trigger()` is an `Event` object, and not a string.

[1]: https://github.com/Dhii/psr-14/blob/master/src/EventManagerInterface.php#L48

**Comment by XedinUnknown** [comment]
@mecha, I've been working on this for a couple of hours now. I'll push hopefully soon, and we can discuss that solution. I think you will like it.

**Comment by mecha** [comment]
Has this been implemented? Can the issue be closed?
